import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "../../app/globals.css";

import {AdvisorContextProvider} from "@/app/_components/content/AdvisorContext"

// archivo font
const inter = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
       <AdvisorContextProvider>
        {children}
       </AdvisorContextProvider>
    );
}
