
import type { Metadata } from "next";
import localFont from "next/font/local";
import {Archivo} from "next/font/google";
import "./globals.css";
import {IndexContextProvider} from "@/app/_context/index"
// archivo font
const inter = Archivo({ subsets: ["latin"] });

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <IndexContextProvider>
          {children}
        </IndexContextProvider>
        
      </body>
    </html>
  );
}
