import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import { IndexContextProvider } from "@/app/_context/index";
import { Toaster } from "react-hot-toast";
import {ChatContextProvider} from "@/src/content/ChatContent"

// archivo font
const inter = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>
                <Toaster
                    position="top-center"
                    reverseOrder={false}
                    toastOptions={{ duration: 3000 }}
                />
                <IndexContextProvider>
                    <ChatContextProvider>
                    {children}
                    </ChatContextProvider>
                </IndexContextProvider>
            </body>
        </html>
    );
}
